version: '3.8'

services:
  ai-interviewer:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./resumes:/app/resumes
      - ./interview_sessions:/app/interview_sessions
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/sessions"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s